### ISSUE TITLE
Adding cast of show searched by the user

### ISSUE THREAD

**Issue by Riturajseal2001** [ietebitmesra/Hacktoberfest-21#109]
When the user searches for a tv series the cast of the show will also be shown

**Comment by Riturajseal2001** [comment]
Can I work on this?

**Comment by dubeyaditya6232** [comment]
Thank you for participating! Since you have opened this issue i assign u with this issue.

**Comment by Riturajseal2001** [comment]
I have created a pull request regarding this issue. Please review it.
