### ISSUE TITLE
All issues are now shifted to the new repo.

### ISSUE THREAD

**Issue by hrc-init** [ietebitmesra/Hacktoberfest-21#159]
Please make your prs there.

**Comment by DearDhruv** [comment]
**Ninja technic - how to get star and forks immediately.**

**Comment by DearDhruv** [comment]
A sane mind could have created diff repo for the obvious need, but no, move it and waste others' contributions on Github.

**Comment by hrc-init** [comment]
The repo was excluded by hacktoberfest due to some changes in their policies this year, so we have to close it(not the other way around). Not only you, but everyone including us lost our progress. We value your contribution but nothing can be done about it now.
Thanks.
