### ISSUE TITLE
Present the searched show with basic details (summary, rating) [Task-3]

### ISSUE THREAD

**Issue by hrcz** [ietebitmesra/Hacktoberfest-21#43]
Name and poster are already there... try to add Summary and Ratings of the particular(searched) show as well.

**Comment by clary09** [comment]
i would like to add

**Comment by sakpab2602** [comment]
Dear @clary09 thank you for your interest in this issue, I am assigning you this issue, hope to see something interesting!

**Comment by clary09** [comment]
thanks!
