### ISSUE TITLE
random html tags (<b>, <p>, etc...) are coming in between summary of shows

### ISSUE THREAD

**Issue by hrcz** [ietebitmesra/Hacktoberfest-21#54]
![msQc0R2](https://user-images.githubusercontent.com/48386941/135711503-1c79c378-456c-4b62-b7e7-8c445f810925.png)

**Comment by sahilsaini110** [comment]
i could take this?

**Comment by sahilsaini110** [comment]
I got the issue, could i take this?

**Comment by clary09** [comment]
i would like to contribute.

**Comment by harshitcodes1** [comment]
I would like to contribute.  I am very much interested.

**Comment by parzival272000** [comment]
Interested

**Comment by sakpab2602** [comment]
@harshitcodes1 I have assigned you to this issue, hope to see some nice results

**Comment by mayukhpankaj** [comment]
![image](https://user-images.githubusercontent.com/40158577/135726480-00069c21-a884-4882-9403-7dd49272fa06.png)
Closing, Fixed !
