### ISSUE TITLE
adding hover property on buttons and background in navbar 

### ISSUE THREAD

**Issue by harmanpreet7916** [ietebitmesra/Hacktoberfest-21#76]
I want to work on task1. I will add my card and I want also want to add hover property on button and background on navbar to beautify the page . I want to do this task under the hacktoberfest-accepted label please assign me this issue.

**Comment by hrcz** [comment]
You are now assigned for this issue.
We will label you hacktoberfest-accepted when we get the pr. 
Thanks for participation :)
