### ISSUE TITLE
show rating stars

### ISSUE THREAD

**Issue by mayukhpankaj** [ietebitmesra/Hacktoberfest-21#82]
![image](https://user-images.githubusercontent.com/40158577/135725960-1cd89d91-17bb-4b4c-b3d1-a92512341e18.png)

Instead of showing Just one star with Rating value, Show Multiple stars. 
If Rating is 8.5 then show 8 yellow stars out of 10 stars.  (*2 stars greyed out)

![image](https://user-images.githubusercontent.com/40158577/135726197-26068243-931d-4985-9b65-e8f340047171.png)

<br>
Good luck ! 
<br>
PS. Rendering fraction of star for decimal value will be great.

**Comment by clary09** [comment]
interested !

**Comment by mayukhpankaj** [comment]
Assigne to @clary09
